owncloud/search_elastic

.drone.starlark
tests/unit/Command/RebuildTest.php
tests/unit/lib/TestSearchElasticConfigService.php
vendor-bin/owncloud-codestyle/composer.json

like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
Note: there was no effect here on `.drone.yml`

Coding standard 2.0.0

---

tests/acceptance/features/apiLimitSearches/indexOnlyMetadata.feature
tests/acceptance/features/apiLimitSearches/limitAccessToGroups.feature
tests/acceptance/features/apiSearchElastic/searchContent.feature
tests/acceptance/features/apiSearchElastic/searchSharedFiles.feature
vendor-bin/behat/composer.json

Needed because of owncloud/core#36999

[Tests-Only] Update guzzle for testing to 6.5

---

lib/Command/Rebuild.php
lib/Command/Reset.php
lib/Search/ElasticSearchResult.php
phpstan.neon
vendor-bin/phpstan/composer.json

@phil-davis could be helpful for #165 
I am not sure, needs more testing

Update phpstan to latest, fix code styling

---

composer.lock

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
- Updating psr/log (1.1.2 => 1.1.3): Loading from cache
```

Updating psr/log (1.1.2 => 1.1.3)

---

tests/unit/Command/RebuildTest.php
tests/unit/Command/UpdateTest.php
vendor-bin/behat/composer.json

Part of https://github.com/owncloud/QA/issues/647

[Tests-Only] Implement phpunit v8

---

tests/acceptance/features/apiLimitSearches/indexOnlyMetadata.feature
tests/acceptance/features/apiLimitSearches/limitAccessToGroups.feature
tests/acceptance/features/apiSearchElastic/searchContent.feature
tests/acceptance/features/apiSearchElastic/searchSharedFiles.feature
tests/acceptance/features/webUISearchElastic/searchContent.feature
tests/acceptance/features/webUISearchElastic/searchSharedFiles.feature

like was done in core last week.
Fixes CI

[tests-onlky] Specify skeleton in tests

---

.drone.star

from activity app.
It will be good to have the latest starlark code, before adjusting to support Elastic Search 7.

[tests-only] Apply latest drone starlark code

---

.drone.star

There were a couple of pending changes to `.drone.star` from recent work in other apps. Apply the changes here for consistency.
Note: after getting this code up-to-date, we can make the general starlark formatting change like in https://github.com/owncloud/activity/pull/991

[tests-only] Apply latest .drone.star

---

.drone.star

Same as https://github.com/owncloud/activity/pull/991
This will get `.drone.star` up-to-date before we touch it again for ES7 support.

[tests-only] Replace tabs with spaces in .drone.star and add check-starlark pipeline

---

.drone.star
appinfo/info.xml
composer.json
composer.lock
lib/Search/ElasticSearchProvider.php

Part of issue https://github.com/owncloud/core/issues/39134
and https://github.com/owncloud/QA/issues/687

Update .drone.star for 'drop PHP 7.2 support'

---

sonar-project.properties

Drop PHP 7.2 in sonar-project.properties

---

tests/acceptance/features/apiSearchElastic/searchWildcard.feature

Add API acceptance tests for search using wildcard pattern.
Fixes https://github.com/owncloud/search_elastic/issues/235
Related https://github.com/owncloud/docs/pull/4155

[Tests-Only] Add tests for search using wildcard pattern

---

lib/ElasticLogger.php
lib/Jobs/SearchJobList.php
lib/Jobs/UpdateContent.php
lib/Search/ElasticSearchProvider.php
lib/SearchElasticService.php

Remove unnessary phan error ignore comments and add description comments for why errors are ignored.
fixes https://github.com/owncloud/search_elastic/issues/232

remove unnecessary phan error ignore comments

---

tests/acceptance/features/bootstrap/SearchElasticContext.php
tests/acceptance/features/bootstrap/WebUIElasticSearchContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/ElasticSearchResultInOtherFoldersPage.php

Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script

[Tests-Only] enforce strict type checking in acceptace tests code

---

lib/Jobs/UpdateContent.php

Issue: https://github.com/owncloud/enterprise/issues/4944
Validate if there are elastic search servers configured before indexing the nodes pending updates.

Verify that there is a configured connection before indexing nodes.

---

css/settings/admin.css
js/settings/admin.js
lib/SearchElasticConfigService.php
templates/settings/admin.php

Issue: https://github.com/owncloud/search_elastic/issues/246
Add user and password authentication.

Add user and password authentication.

---

README.md

@mmattel Please merge after the doc part is done.

docs: cleanup readme and add backlink to documentation

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties
templates/settings/admin.php

merge back to master after release

Release 2.2.0

---

tests/acceptance/features/apiLimitSearches/indexOnlyMetadata.feature
tests/acceptance/features/apiLimitSearches/limitAccessToGroups.feature
tests/acceptance/features/apiSearchElastic/searchContent.feature
tests/acceptance/features/apiSearchElastic/searchSharedFiles.feature
tests/acceptance/features/webUISearchElastic/searchContent.feature
tests/acceptance/features/webUISearchElastic/searchSharedFiles.feature

Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
- :robot:

[full-ci] [tests-only] Refactored inter scenarios space

---

.drone.star

There have been a few changes and enhancements to the common drone code of oC10 apps.
Apply them here.

[tests-only] [full-ci] Update .drone.star common code from activity app

---

lib/Command/Rebuild.php

I guess the command which should be used is `rebuild` as there is no `build` command

Fixed command suggestion

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

Release 2.3.0

---

tests/acceptance/features/webUISearchElastic/searchContent.feature

Part of: owncloud/QA#825
> Note: This PR was made by an automated script, in case something is not right I'll take care of it manually.

[tests-only] fix the line syntax
